name: Run builds on supported distributions

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-combined:
     uses: ./.github/workflows/build-combined.yml
     with:
       # libsrepo: svarshavchik/courier-libs
       libsrepo: svarshavchik/courier-libs-scratchpad
       libsbranch: master
